<#
 Makes IIS forward the Strive hostnames to the containers (run in an elevated PowerShell).

 - adds ONE new site "strive-proxy" with its own bindings for the four hostnames (the other sites are not touched)
 - installs nothing: URL Rewrite and Application Request Routing (ARR) must be installed before, see README.md
 - uses the wildcard certificate that is in the certificate store (by default the one for *.<domain>)

   .\Setup-Iis.ps1
#>
param([string] $CertificateSubject = '')
$ErrorActionPreference = 'Stop'
Import-Module WebAdministration

$env = Join-Path (Split-Path (Split-Path $PSScriptRoot)) 'src\.env.production'
$vars = @{}; Get-Content $env | ForEach-Object { if ($_ -match '^([A-Z0-9_]+)=(.*)$') { $vars[$Matches[1]] = $Matches[2] } }
$domain = $vars.SITE_HOST
$hosts = [ordered]@{
   $vars.FRONTEND_DNS_OR_IP = 5003   # web app
   "api.$domain"            = 5002   # strive
   "identity.$domain"       = 5001   # sign in
   "sfu.$domain"            = 5004   # media server signaling
}

foreach ($module in 'Rewrite', 'ApplicationRequestRouting') {
   if (-not (Get-WebGlobalModule | Where-Object Name -like "*$module*")) { throw "IIS module $module is missing. Install URL Rewrite and ARR first (README.md)." }
}
if (-not (Get-WindowsFeature Web-WebSockets).Installed) { Install-WindowsFeature Web-WebSockets | Out-Null; Write-Host 'Installed the IIS WebSocket feature.' }

# the certificate
if (-not $CertificateSubject) { $CertificateSubject = "*.$domain" }
$cert = Get-ChildItem Cert:\LocalMachine\My, Cert:\LocalMachine\WebHosting -ErrorAction SilentlyContinue |
   Where-Object { $_.Subject -like "*CN=$CertificateSubject*" -or $_.DnsNameList.Unicode -contains $CertificateSubject } |
   Sort-Object NotAfter -Descending | Select-Object -First 1
if (-not $cert) { throw "No certificate for $CertificateSubject in the machine store. Pass -CertificateSubject." }
Write-Host "Certificate: $($cert.Subject) (expires $($cert.NotAfter))"
$storeName = if ($cert.PSParentPath -like '*WebHosting*') { 'WebHosting' } else { 'My' }

# ARR: proxy on, long timeout (websockets and long polling), keep the host name
Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter 'system.webServer/proxy' -Name 'enabled' -Value 'True'
Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter 'system.webServer/proxy' -Name 'timeout' -Value '01:00:00'
Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter 'system.webServer/proxy' -Name 'preserveHostHeader' -Value 'True'

# the site
$root = 'C:\inetpub\strive-proxy'
New-Item -ItemType Directory -Force -Path $root | Out-Null
$rules = ($hosts.GetEnumerator() | ForEach-Object {
   $pattern = '^' + [regex]::Escape($_.Key) + '$'
   @"
        <rule name="$($_.Key)" stopProcessing="true">
          <match url="(.*)" />
          <conditions><add input="{HTTP_HOST}" pattern="$pattern" /></conditions>
          <serverVariables>
            <set name="HTTP_X_FORWARDED_PROTO" value="https" />
          </serverVariables>
          <action type="Rewrite" url="http://127.0.0.1:$($_.Value)/{R:1}" />
        </rule>
"@
}) -join "`r`n"

@"
<?xml version="1.0" encoding="utf-8"?>
<!-- generated by deploy/windows/Setup-Iis.ps1, run it again instead of editing -->
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
$rules
      </rules>
    </rewrite>
    <security><requestFiltering><requestLimits maxAllowedContentLength="104857600" /></requestFiltering></security>
  </system.webServer>
</configuration>
"@ | Set-Content -Encoding UTF8 (Join-Path $root 'web.config')

if (-not (Get-Website -Name 'strive-proxy' -ErrorAction SilentlyContinue)) {
   $first = $hosts.Keys | Select-Object -First 1
   New-Website -Name 'strive-proxy' -PhysicalPath $root -HostHeader $first -Port 80 -Force | Out-Null
}
# other hostnames and https bindings (SNI), existing ones are kept
foreach ($h in $hosts.Keys) {
   if (-not (Get-WebBinding -Name 'strive-proxy' -Protocol http -HostHeader $h -ErrorAction SilentlyContinue)) {
      New-WebBinding -Name 'strive-proxy' -Protocol http -Port 80 -HostHeader $h
   }
   if (-not (Get-WebBinding -Name 'strive-proxy' -Protocol https -HostHeader $h -ErrorAction SilentlyContinue)) {
      New-WebBinding -Name 'strive-proxy' -Protocol https -Port 443 -HostHeader $h -SslFlags 1
   }
   (Get-WebBinding -Name 'strive-proxy' -Protocol https -HostHeader $h).AddSslCertificate($cert.Thumbprint, $storeName)
}

# the server variable that the rules set must be allowed
$filter = 'system.webServer/rewrite/allowedServerVariables'
$existing = Get-WebConfiguration -Filter "$filter/add[@name='HTTP_X_FORWARDED_PROTO']" -PSPath 'MACHINE/WEBROOT/APPHOST/strive-proxy'
if (-not $existing) {
   Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location 'strive-proxy' -Filter $filter -Name '.' -Value @{ name = 'HTTP_X_FORWARDED_PROTO' }
}

Start-Website -Name 'strive-proxy' -ErrorAction SilentlyContinue
Write-Host "Done. Hostnames: $($hosts.Keys -join ', ')"
Write-Host 'Check: https://<host>/ in a browser once the containers run (.\strive.ps1 up).'
