name: ASP.NET Core
on:
  push:
    paths:
      - src/**
      - .github/workflows/asp-net-core-test.yml
      - codecov.yml
      - "!src/Services/SFU/**"
      - "!src/Web/WebSPA/Client/**"
      - "!src/Tests/e2e/**"

  pull_request:
    branches:
      - develop
    paths:
      - src/**
      - .github/workflows/asp-net-core-test.yml
      - codecov.yml
      - "!src/Services/SFU/**"
      - "!src/Web/WebSPA/Client/**"
      - "!src/Tests/e2e/**"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # Strive.Infrastructure.Redis.Tests run against localhost:6379
      redis:
        image: redis:7
        ports:
          - 6379:6379
    defaults:
      run:
        working-directory: src/
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore Strive.sln
      - name: Test
        run: dotnet test Strive.sln --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
